# Title: Build the ObservaBio CSS bundle
# Concatenates the modular sources in inst/app/www/css/ (numeric order) into a
# single inst/app/www/custom.css served by run_app()'s addResourcePath("www").
# Run after editing any source file: Rscript data-raw/build_css.R
# Same mechanism as Saira; the styles are ObservaBio-original (docs/design.md).

build_css <- function(css_dir = "inst/app/www/css",
                      out = "inst/app/www/custom.css") {
  if (!dir.exists(css_dir)) {
    stop(sprintf("CSS source dir not found: %s", css_dir))
  }
  sources <- sort(list.files(css_dir, pattern = "\\.css$", full.names = TRUE))
  if (length(sources) == 0L) {
    stop(sprintf("No .css sources found in %s", css_dir))
  }

  header <- c(
    "/* ======================================================================",
    " * ObservaBio custom.css — GENERATED by data-raw/build_css.R. DO NOT EDIT.",
    " * Edit the sources in inst/app/www/css/ and rebuild.",
    sprintf(" * Built: %s", format(Sys.time(), "%Y-%m-%d %H:%M:%S")),
    " * ==================================================================== */",
    ""
  )

  chunks <- lapply(sources, function(f) {
    c(sprintf("/* --- %s --- */", basename(f)), readLines(f, warn = FALSE), "")
  })

  writeLines(c(header, unlist(chunks)), out)
  message(sprintf("Wrote %s from %d sources.", out, length(sources)))
  invisible(out)
}

if (identical(environment(), globalenv())) {
  build_css()
}
