# Title: Build the ObservaBio deploy artifacts (renv.lock + manifest.json + .posit)
# Run before publishing:            Rscript data-raw/build_deploy.R
# Verify the lock is still current: Rscript data-raw/build_deploy.R --check
# Runbook and platform notes: docs/deploy.md. Rationale: docs/DECISIONS.md.
#
# Why a lockfile but no renv::init(): activating renv would write .Rprofile +
# renv/activate.R, and neither survives contact with this repo. The validation
# commands in .claude/CLAUDE.md run `Rscript --vanilla`, which ignores .Rprofile
# — renv would be silently inactive exactly where we validate. CI installs deps
# with pak into the system library (r-lib/actions/setup-r-dependencies), which a
# committed .Rprofile would fight. The lockfile alone gives what the contract
# asks for: pinned versions that rsconnect reads at deploy time.
#
# Why an allowlist and not .rscignore: rsconnect bundles from the FILESYSTEM,
# not from git, so the gitignored client spreadsheets at the repo root and the
# 185 MB of raw base downloads under data-raw/tmp/ would ship to a public URL.
# .rscignore is a denylist with no wildcard support — one new spreadsheet
# dropped at the root and it leaks. appFiles inverts that: only what is listed
# ships, so omission fails closed.

CRAN_REPO <- "https://cloud.r-project.org"

#' Version ceilings imposed by the deploy platform's system libraries
#'
#' Posit Connect Cloud builds on Ubuntu 22.04 (GDAL 3.4.1, PROJ 8.2.1, GEOS
#' 3.10.2) and gives no way to install system packages — no sudo, no apt, no
#' Dockerfile. So a pinned R package that needs a newer system library cannot be
#' fixed on the server; the only lever is which version we pin here.
#'
#' The failure mode is nastier than "too new": Posit's package manager publishes
#' a prebuilt jammy binary only for versions that compile there, so a version
#' past the ceiling silently falls back to a **source** build on Connect Cloud
#' and dies mid-compile. `terra` 1.9-34 does exactly that — it calls the
#' 3-argument `GDALMDArray::AsClassicDataset()`, which GDAL 3.4.1 does not have.
#' 1.9-27 is the newest version with a jammy binary (versions in between are
#' untested). Local dev on a newer distro never reproduces it: Ubuntu 24.04
#' ships GDAL 3.8.4, where 1.9-34 compiles fine. See docs/LESSONS.md L-016.
#'
#' Re-check a ceiling before raising it — a binary exists iff the tarball
#' unpacks with a `libs/` directory:
#'
#'     curl -sL -A "R (4.5.2 x86_64-pc-linux-gnu x86_64 linux-gnu)" \
#'       https://packagemanager.posit.co/cran/__linux__/jammy/latest/src/contrib/terra_<ver>.tar.gz \
#'       | tar tz | grep terra/libs/
PLATFORM_MAX_VERSION <- c(terra = "1.9-27")

`%||%` <- function(x, y) if (is.null(x)) y else x

#' Fail if any pinned version exceeds what the deploy platform can build
#'
#' Runs on both paths (build and --check) because the regression arrives by
#' accident: a routine `update.packages()` on the dev machine is enough to raise
#' terra past the ceiling, and everything local stays green.
check_platform_ceiling <- function(lock) {
  for (pkg in names(PLATFORM_MAX_VERSION)) {
    record <- lock$Packages[[pkg]]
    if (is.null(record)) {
      next
    }
    ceiling <- PLATFORM_MAX_VERSION[[pkg]]
    if (package_version(record$Version) > package_version(ceiling)) {
      stop(sprintf(paste0(
        "%s %s exceeds the deploy platform ceiling (%s).\n",
        "Connect Cloud (Ubuntu 22.04) has no prebuilt binary for it and the ",
        "source build fails.\nDowngrade locally, then rebuild:\n",
        "  Rscript --vanilla -e 'renv::install(\"%s@%s\", prompt = FALSE)'"),
        pkg, record$Version, ceiling, pkg, ceiling))
    }
  }
  invisible(TRUE)
}

#' Files that make up the deploy bundle (the allowlist)
#'
#' The package source (R/, DESCRIPTION, NAMESPACE) plus inst/ (embedded bases
#' and www assets) plus the entrypoint and the lock. Everything else —
#' data-raw/, docs/, tests/, client data, the proposal .docx — stays out by
#' construction.
deploy_files <- function() {
  root <- c("app.R", "DESCRIPTION", "NAMESPACE", "LICENSE.md", "NOTICE.md",
            "renv.lock")
  # renv.lock is generated by this script, so it may legitimately not exist yet.
  missing <- setdiff(root[!file.exists(root)], "renv.lock")
  if (length(missing)) {
    stop(sprintf("Missing required bundle file(s): %s",
                 paste(missing, collapse = ", ")))
  }
  nested <- unlist(lapply(c("R", "inst"), function(d) {
    file.path(d, list.files(d, recursive = TRUE, all.files = FALSE))
  }))
  c(root[file.exists(root)], nested)
}

#' Build the lockfile object from DESCRIPTION (explicit snapshot)
#'
#' `type = "explicit"` snapshots Imports/Depends/LinkingTo plus their recursive
#' dependencies — the runtime set — instead of everything installed. Suggests
#' (testthat, devtools, geobr, ...) stay out of the bundle on purpose.
#' The repos option must be set explicitly: under `--vanilla` it is "@CRAN@",
#' which would land in the lock as an unresolvable repository.
lock_object <- function() {
  options(repos = c(CRAN = CRAN_REPO))
  renv::lockfile_create(project = ".", type = "explicit", prompt = FALSE)
}

#' Compact "package version source" view of a lockfile, for comparison
lock_signature <- function(lock) {
  pkgs <- lock$Packages
  if (!length(pkgs)) {
    return(character(0))
  }
  sig <- vapply(
    pkgs,
    function(p) paste(p$Package, p$Version, p$Source %||% NA_character_),
    character(1)
  )
  sort(unname(sig))
}

build_lock <- function(path = "renv.lock") {
  lock <- lock_object()
  check_platform_ceiling(lock)
  renv::lockfile_write(lock, file = path)
  message(sprintf("Wrote %s (%d packages, R %s).",
                  path, length(lock$Packages), lock$R$Version))
  invisible(path)
}

#' Write manifest.json from the allowlist
#'
#' rsconnect's default `dependencyResolution = "strict"` reads renv.lock when it
#' is present, so the manifest inherits the pinned versions rather than
#' re-snapshotting whatever happens to be installed. Posit Connect Cloud reads
#' only the manifest (it does not consume renv.lock), which is why this file is
#' committed rather than generated at deploy time.
build_manifest <- function(path = "manifest.json") {
  if (!file.exists("renv.lock")) {
    stop("renv.lock is missing — run this script without --check first.")
  }
  rsconnect::writeManifest(
    appDir = ".",
    appFiles = deploy_files(),
    appPrimaryDoc = "app.R"
  )
  manifest <- jsonlite::fromJSON(path)
  message(sprintf("Wrote %s (%d packages, R %s, %d bundled files).",
                  path, length(manifest$packages), manifest$platform,
                  length(manifest$files)))
  invisible(path)
}

#' Sync the Posit Publisher config's file list with the manifest allowlist
#'
#' The IDE route (`rsconnect::deployApp()` / Posit Publisher) does NOT read
#' `manifest.json` — it bundles whatever `.posit/publish/<name>.toml` lists under
#' `files`. Publisher generates that list by scanning the entrypoint, and `app.R`
#' names no files: it calls `pkgload::load_all(".")`. So the generated list is
#' just app.R + renv.lock, the bundle lands on the server without `DESCRIPTION`,
#' `R/` or `inst/`, and the app dies at boot with "Could not find a root
#' 'DESCRIPTION' file". Rewriting the list from `deploy_files()` keeps both routes
#' fed from one source of truth.
#'
#' The `deployments/*.toml` records are Publisher's own output ("do not edit") and
#' are left alone.
#'
#' @return The config paths written (invisibly).
build_posit_config <- function() {
  dir <- file.path(".posit", "publish")
  configs <- list.files(dir, pattern = "\\.toml$", full.names = TRUE)
  if (length(configs) == 0L) {
    message("NOTE: no .posit/publish/*.toml — IDE route not configured here yet.")
    return(invisible(character(0)))
  }
  # Publisher lists its own config and deployment records in the bundle; keep that.
  own <- file.path(dir, list.files(dir, recursive = TRUE))
  wanted <- unique(c(deploy_files(), own))

  for (path in configs) {
    lines <- readLines(path, warn = FALSE)
    open_at <- grep("^files\\s*=\\s*\\[", lines)
    if (length(open_at) != 1L) {
      stop(sprintf("Expected exactly one `files = [` block in %s, found %d.",
                   path, length(open_at)))
    }
    tail_lines <- lines[(open_at + 1L):length(lines)]
    close_rel <- which(grepl("^\\]", tail_lines))[1L]
    if (is.na(close_rel)) {
      stop(sprintf("Unterminated `files = [` block in %s.", path))
    }
    close_at <- open_at + close_rel
    block <- c("files = [", sprintf('    "/%s",', wanted), "]")
    writeLines(
      c(lines[seq_len(open_at - 1L)], block,
        if (close_at < length(lines)) lines[(close_at + 1L):length(lines)]),
      path
    )
    message(sprintf("Wrote %s (%d bundled files).", path, length(wanted)))
  }
  invisible(configs)
}

#' Verify the committed artifacts still match the local library
#'
#' The lock is a hard gate: a mismatch means the deploy would install versions
#' nobody validated. The manifest is a soft gate — it stores a checksum per
#' bundled file, so it goes stale on every code commit by design; only its
#' package set is worth comparing.
check_deploy <- function() {
  if (!file.exists("renv.lock")) {
    stop("renv.lock not found. Run: Rscript data-raw/build_deploy.R")
  }
  check_platform_ceiling(renv::lockfile_read("renv.lock"))
  fresh <- lock_signature(lock_object())
  committed <- lock_signature(renv::lockfile_read("renv.lock"))

  if (!identical(fresh, committed)) {
    added <- setdiff(fresh, committed)
    dropped <- setdiff(committed, fresh)
    if (length(added)) {
      message("Local library has, lock does not:\n  ",
              paste(added, collapse = "\n  "))
    }
    if (length(dropped)) {
      message("Lock has, local library does not:\n  ",
              paste(dropped, collapse = "\n  "))
    }
    stop("renv.lock is out of date. Run: Rscript data-raw/build_deploy.R")
  }
  message(sprintf("renv.lock is current (%d packages).", length(committed)))

  if (file.exists("manifest.json")) {
    manifest_pkgs <- sort(names(jsonlite::fromJSON("manifest.json")$packages))
    lock_pkgs <- sort(names(renv::lockfile_read("renv.lock")$Packages))
    if (!identical(manifest_pkgs, lock_pkgs)) {
      message("NOTE: manifest.json package set differs from renv.lock. ",
              "Regenerate before deploying.")
    } else {
      message("manifest.json package set matches renv.lock.")
    }
  } else {
    message("NOTE: manifest.json not found — required by Posit Connect Cloud.")
  }
  invisible(TRUE)
}

if (identical(environment(), globalenv())) {
  if ("--check" %in% commandArgs(trailingOnly = TRUE)) {
    check_deploy()
  } else {
    build_lock()
    build_manifest()
    build_posit_config()
  }
}
